### ISSUE TITLE
Mise en place du CI/CD

### ISSUE THREAD

**Issue by SamuelLnds** [SamuelLnds/Laravel-Box#22]
Plusieurs étapes à suivre :

1. créer un fichier `.github/workflows/ci.yml` à la racine de votre projet
```
name: CI

on: [push]

jobs:
    deploy:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Push to server
            uses: appleboy/ssh-action@master
            with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: |
                cd ${{ secrets.PROJECT_PATH }}
```

2. Aller voir dans `Actions` sur GitHub pour voir les actions effectuées
3. Définir les variables en paramètre du repository (Settings -> Secrets & variables -> Actions)
